Announce_Format: "&8[&cAlert&8] &r"
Filter_Format: "&cYou can't say that!"
Mute_Format: "&cChat is currently muted!"
Filter_Banned_Words: false
# PLEASE EDIT THIS LIST
Banned_Words:
  - enter
  - banned
  - words
  - here