name: BetterChat
main: com.nexh.bc.Main
version: 1.0.0
commands:
  globalmute:
    aliases: [ mutechat, mc, togglechat, tc ]
    description: Mute global chat.
  clearchat:
    aliases: [ cc, chatclear ]
    description: Clear the server chat.
  bc:
    aliases: [ betterchat, chatbetter ]
    description: Get the commands for the BetterChat plugin.
  broadcast:
    aliases: [ alert, announce, a, ac ]
    description: Broadcast a message to the server.
permissions:
  bc.*:
    description: Gives permission to all the BetterChat commands.
  bc.reload:
    description: Gives permission to reload BetterChat config.
  bc.broadcast:
    description: Gives permission to broadcast messages.
  bc.clearchat:
    description: Gives permission to clear chat.
  bc.mute.global:
    description: Gives permission to mute server chat.
  bc.mute.bypass:
    description: Gives permission to bypass server mute.
  bc.mute.*:
    description: Gives permission for all BetterChat mute commands.
  bc.swear.bypass:
    description: Gives permission to bypass chat filter.